### ISSUE TITLE
startkabel.nl

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/easylistdutch#36]
A considerable amount of ad-links and placeholders on `https://nieuws.startkabel.nl/`. I propose:
```
nieuws.startkabel.nl##.banner
nieuws.startkabel.nl###campagne
(Optional) nieuws.startkabel.nl##a[href*=casino]
```

* Screenshot: 
![image](https://user-images.githubusercontent.com/22780683/149199583-985b7c76-01ee-46e9-962e-a87aef98de50.png)
* OS/version: Windows 11 x64
* Browser/version: Chrome 97.0.4692.71 x64
* Adblock Extension/version: uBO 1.40.5b1
* Subscriptions (Note that I also test with AdGuard Dutch Filter just in case): ![image](https://user-images.githubusercontent.com/22780683/149192842-60ed337d-d6cd-4c83-842b-0aa6a1f94ffe.png)

**Comment by JohnyP36** [comment]
The optional `nieuws.startkabel.nl##a[href*=casino]` is unnecessary, because `###campagne` already block the whole block. 
But I don't know if this block is an ad. 

Second, `nieuws.startkabel.nl##.banner` is already blocked by `startkabel.nl##.banner`
**But that last rule is NOT found in EasyList Dutch**

Third, on my side I don't have those white empty spaces.
