### ISSUE TITLE
Anti-adblock message blocked on tweakers.net

### ISSUE THREAD

**Issue by edivaniadc** [easylist/easylistdutch#59]
**Issue:** Anti-adblock message blocked on tweakers.net

**Sample URL:** https://tweakers.net/reviews/11090/kant-en-klare-malware-onderzoekers-ontrafelen-hoe-illegale-marktplaats-werkte.html

**EasyList Dutch filter causing the issue:** `||aa.tweakers.nl^`

<img width="993" alt="twk" src="https://github.com/easylist/easylistdutch/assets/57706597/dfaf35af-d00d-4c0d-bd91-c7d9591e6b9e">

**Comment by JohnyP36** [comment]
The rules 
```
@@||aa.tweakers.nl/json*$xhr,domain=tweakers.net
@@||ab.tweakers.nl/pool/lib/*.gif$xhr,domain=tweakers.net
```
will solve this

In addition, if `tweakers.net##.widebnr` is blocked, add the following rule too
```
tweakers.net#@#.widebnr
```

**Comment by JohnyP36** [comment]
> @JohnyP36 I'm using ABP

@edivaniadc If you look-up other issues in this repo you will notice that ABP doesn't support anti-adblock rules. 
If you don't want to disable your adblocker use [`uBlock Origin`](https://github.com/gorhill/uBlock) with standard list enabled. 
As the Dutch filter list uBlock is supporting does support anti-adblock, your problem is solved. 

##### if you decide to use uBlock, please report issues regarding Dutch site [here](https://github.com/EasyDutch-uBO/EasyDutch/issues).
